apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-deployment
  labels:
    app: crawler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
      - name: crawler
        image: irisowo/crawler:v2
        ports:
        - containerPort: 80
          name: crawler
        volumeMounts:
          - name: history-dir
            mountPath: /var/log/history
      volumes:
      - name: history-dir
        persistentVolumeClaim:
          claimName: pvc-demo