apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: default
  name: cronjob-crawler
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeName: gk3-project23-default-pool-c96d0be0-h79s
          containers:
          - name: write-file
            image: irisowo/crawler:v1
            volumeMounts:
            - name: history-dir
              mountPath: /sample_crawler/history
          restartPolicy: OnFailure
          volumes:
          - name: history-dir
            persistentVolumeClaim:
              claimName: pvc-demo