# gcloud container clusters update project23 --zone asia-east1 --update-addons=GcpFilestoreCsiDriver=ENABLED
# kubectl create -f filestore-crawler.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: filestore-crawler
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  tier: standard
  network: default