# kubectl create -f pvc-test.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-test
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: filestore-crawler
  resources:
    requests:
      storage: 30Gi