apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: react-app
  template:
    metadata:
      labels:
        component: react-app
    spec:
      containers:
        - name: react-app
          image: irisowo/frontend:v1
          ports:
            - containerPort: 3000