# kubectl create -f pvc-test.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi

---

  apiVersion: v1
  kind: Pod
  metadata:
    name: pod-test
    labels:
      app: crawler
    namespace: default
  spec:
    containers:
    - name: crawler
      image: irisowo/cron:1day
      ports:
      - containerPort: 4000
        name: crawler
      volumeMounts:
        - name: history-dir
          mountPath: /sample_crawler/history
    volumes:
    - name: history-dir
      persistentVolumeClaim:
        claimName: pvc-test

---

apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: default
  name: cronjob-crawler
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: write-file
            image: irisowo/crawler:v1
            volumeMounts:
            - name: history-test
              mountPath: /sample_crawler/history
          restartPolicy: OnFailure
          volumes:
          - name: history-test
            persistentVolumeClaim:
              claimName: pvc-test